package vista;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class GraficosPestana extends javax.swing.JPanel {
    public GraficosPestana() {
        initComponents();
    }
    public void fillGraficasComboBox(String[] graficas){
        for(String item:graficas){
            this.ComboBoxGraficas.addItem(item);
        }
    }
    private void setVisibleProduct(boolean x){
        ProductosComboBox.setVisible(x);
        LabelProducto.setVisible(x);
    }
    private void setVisibleYear(boolean x){
        this.LabelAno.setVisible(x);
        AnoTextField.setVisible(x);
    }
    private void setVisibleMonth(boolean x){
        ComboBoxMeses.setVisible(x);
        LabelMes.setVisible(x);
    }
    public void hideYear(){
        setVisibleYear(false);
    }
    public void unhideYear(){
        setVisibleYear(true);
    }
    public void hideMonth(){
        setVisibleMonth(false);
    }
    public void unhideMonth(){
        setVisibleMonth(true);
    }
    public void hideDate(){
        hideMonth();
        hideYear();
    }
    public void unhideDate(){
        unhideYear();
        unhideMonth();
    }
    public void hideProduct(){
        setVisibleProduct(false);
    }
    public void unhideProduct(){
        setVisibleProduct(true);
    }
    public void clearProductComboBox(){
        ProductosComboBox.removeAllItems();
    }
    public void fillProductComboBox(ResultSet rs){
        try {
            while(rs.next()){
                ProductosComboBox.addItem(rs.getString("nombre"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(GraficosPestana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public int getComboBoxGraficasIndex(){
        return this.ComboBoxGraficas.getSelectedIndex();
    }
    public void addComboBoxActionListener(ActionListener al){
        this.ComboBoxGraficas.addActionListener(al);
    }
    public int getYear(){
        try{
            return Integer.parseInt(AnoTextField.getText().trim());}
        catch(NumberFormatException exeption){
        }
        return -1;
    }
    public int  getMonth(){
        return ComboBoxMeses.getSelectedIndex();
    }
    public String getProduct(){
        return String.valueOf(ProductosComboBox.getSelectedItem());
    }
    public void addALButton(ActionListener al){
        this.ButtonGraficar.addActionListener(al);
    }
    public JButton getButtonGraficar(){
        return ButtonGraficar;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBoxGraficas = new JComboBox<>();
        LabelMes = new javax.swing.JLabel();
        LabelAno = new javax.swing.JLabel();
        ComboBoxMeses = new javax.swing.JComboBox<>();
        ButtonGraficar = new javax.swing.JButton();
        Text1_1 = new javax.swing.JLabel();
        Text1_2 = new javax.swing.JLabel();
        AnoTextField = new javax.swing.JTextField();
        LabelProducto = new javax.swing.JLabel();
        ProductosComboBox = new javax.swing.JComboBox<>();

        setBackground(java.awt.Color.darkGray);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(300, 150));
        setPreferredSize(new java.awt.Dimension(450, 300));

        ComboBoxGraficas.setBackground(java.awt.Color.darkGray);
        ComboBoxGraficas.setForeground(java.awt.Color.white);
        ComboBoxGraficas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ComboBoxGraficas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxGraficasActionPerformed(evt);
            }
        });

        LabelMes.setForeground(java.awt.Color.white);
        LabelMes.setText("Mes:");

        LabelAno.setForeground(java.awt.Color.white);
        LabelAno.setText("Año:");

        ComboBoxMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octumbre", "Noviembre", "Diciembre" }));
        ComboBoxMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMesesActionPerformed(evt);
            }
        });

        ButtonGraficar.setText("Graficar");
        ButtonGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGraficarActionPerformed(evt);
            }
        });

        Text1_1.setForeground(java.awt.Color.white);
        Text1_1.setText("Seleccione la gráfica que");

        Text1_2.setForeground(java.awt.Color.white);
        Text1_2.setText(" desee visualizar:");

        AnoTextField.setMaximumSize(new java.awt.Dimension(96, 26));
        AnoTextField.setMinimumSize(new java.awt.Dimension(96, 26));
        AnoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnoTextFieldActionPerformed(evt);
            }
        });

        LabelProducto.setForeground(new java.awt.Color(255, 255, 255));
        LabelProducto.setText("Producto:");

        ProductosComboBox.setMaximumSize(new java.awt.Dimension(96, 26));
        ProductosComboBox.setMinimumSize(new java.awt.Dimension(96, 26));
        ProductosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Text1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text1_2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(ComboBoxGraficas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(ButtonGraficar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelAno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelProducto))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AnoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ProductosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboBoxMeses, 0, 157, Short.MAX_VALUE))))
                        .addContainerGap(125, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text1_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text1_2))
                    .addComponent(ComboBoxGraficas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelProducto)
                    .addComponent(ProductosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonGraficar)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMesesActionPerformed

    private void ButtonGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGraficarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonGraficarActionPerformed

    private void AnoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnoTextFieldActionPerformed

    private void ComboBoxGraficasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxGraficasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxGraficasActionPerformed

    private void ProductosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductosComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnoTextField;
    private javax.swing.JButton ButtonGraficar;
    private javax.swing.JComboBox<String> ComboBoxGraficas;
    private javax.swing.JComboBox<String> ComboBoxMeses;
    private javax.swing.JLabel LabelAno;
    private javax.swing.JLabel LabelMes;
    private javax.swing.JLabel LabelProducto;
    private javax.swing.JComboBox<String> ProductosComboBox;
    private javax.swing.JLabel Text1_1;
    private javax.swing.JLabel Text1_2;
    // End of variables declaration//GEN-END:variables
}
